import sbt._

import sbt.Keys._
import com.github.sbt.git.SbtGit.git
import play.core.PlayVersion

object BuildInfo {
  lazy val createBuildInfoFileTask: Def.Initialize[Task[Seq[File]]] = Def.task {
    val currentCommitHash = git.gitHeadCommit.value.getOrElse("None")
    val output = (Compile / sourceManaged).value / "kindleclock" / "domain" / "lib" / "BuildInfo.scala"

    val versionsBody =
      s"""/**
         |  * This file was generated by `project/BuildInfo.scala`.
         |  * So you must not edit this file.
         |  */
         |
         |package kindleclock.domain.lib
         |
         |object BuildInfo {
         |  val scalaVersion: String = "${scalaVersion.value}"
         |  
         |  val commitHash: String = "${currentCommitHash}"
         |
         |  val playVersion: String = "${PlayVersion.current}"
         |}
         |""".stripMargin

    IO.write(output, versionsBody)
    Seq(output)
  }
}
